jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Install libarchive
        run: |
          wget https://www.libarchive.org/downloads/libarchive-3.4.2.tar.gz
          tar xvf libarchive-3.4.2.tar.gz
          cd libarchive-3.4.2
          ./configure
          make -j
          sudo make install
      - uses: "actions/checkout@v1"
      - id: setup-haskell-cabal
        uses: "actions/setup-haskell@v1.1"
        with:
          cabal-version: "${{ matrix.cabal }}"
          ghc-version: "${{ matrix.ghc }}"
      - uses: "actions/cache@v1"
        with:
          key: "${{ runner.os }}-${{ matrix.ghc }}-cabal"
          path: "${{ steps.setup-haskell-cabal.outputs.cabal-store }}"
      - name: Install dependencies
        run: |
          cabal update
          cabal build --enable-tests --enable-benchmarks --only-dependencies
      - name: build
        run: cabal build --enable-tests --enable-benchmarks
      - name: test
        run: cabal test 
      - name: haddock
        run: cabal haddock 
    strategy:
      matrix:
        cabal:
          - '3.2'
        ghc:
          - '8.4.4'
          - '8.6.5'
          - '8.8.3'
name: Haskell CI
on:
  - push
